---
- name: Converge
  hosts: all
  roles:
    - role: fail2ban-versions

  post_tasks:
    - name: Check fail2ban-client works
      command: "fail2ban-client"
      changed_when: false
#      args:
#        chdir: /tmp/git-project/fail2ban/
